name: CI/CD Deployment to Azure

on:
  push:
    branches:
      - main  # Change karein agar kisi aur branch par deploy karna ho

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js (Agar Node App hai)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-azure-app-name"
          package: "."

  local-run:
    runs-on: self-hosted  # Local machine par GitHub runner hona zaroori hai
    needs: deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Local Server
        run: npm start
