
name: Build and Deploy Node.js App to Azure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the appropriate Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional)
      - name: Run Tests
        run: npm test

      # Build the application (if needed)
      - name: Build Application
        run: npm run build  # Modify this if your project requires a build step

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the app to Azure Web Apps
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-nodejs-app"  # Replace with your Azure Web App name
          slot-name: "production"
          package: "."
