name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your deployment branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Ensure you have tests, or replace this with your test command

      - name: Build Project (If Needed)
        run: npm run build  # Use only if you have a build step

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}  # Add this in GitHub Secrets
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /var/www/my-node-app  # Change to your deployment path
            git pull origin main
            npm install
            pm2 restart app  # Ensure you have PM2 installed for process management
